org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
org.gradle.parallel=true
org.gradle.caching=true
android.useAndroidX=true
android.nonTransitiveRClass=true
kotlin.code.style=official
org.gradle.java.home=C:\\Users\\hilla.DESKTOP\\AppData\\Local\\Packages\\Microsoft.4297127D64EC6_8wekyb3d8bbwe\\LocalCache\\Local\\runtime\\java-runtime-beta\\windows-x64\\java-runtime-beta

# Enabled parallel sync for Gradle 9.4+
org.gradle.tooling.parallel=true
